version: '2'
services:
  test-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/Test/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=Test
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
